server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/test
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: user-service
logging:
  level:
    root: INFO
    com.example: DEBUG
